name: CD Pipeline for 3-Tier App

on:
  workflow_run:
    workflows:
      - CI Pipeline for 3-Tier App
    types:
      - completed

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    # Step 3: Update kubeconfig
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-west-1 --name kris-eks-cluster

    # Step 4: Deploy to EKS
    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f ./K8s/frontend.yaml
        kubectl apply -f ./K8s/backend.yaml
        kubectl apply -f ./K8s/postgres.yaml
