name: CI Pipeline for 3-Tier App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      BACKEND_IMAGE: backend
      FRONTEND_IMAGE: frontend

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Step 4: Build and Push Backend Image
    - name: Build and Push Backend Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest ./api
        docker tag $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest $DOCKERHUB_USERNAME/$BACKEND_IMAGE:${{ github.sha }}
        docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest
        docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:${{ github.sha }}

    # Step 5: Build and Push Frontend Image
    - name: Build and Push Frontend Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest ./ui
        docker tag $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:${{ github.sha }}
        docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest
        docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:${{ github.sha }}
