name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push Frontend Image
      run: |
        docker build -t krisssssssss/frontend:v2 ./frontend
        docker push krisssssssss/frontend:v2

    - name: Build and Push Backend Image
      run: |
        docker build -t krisssssssss/backend:v2 ./backend
        docker push krisssssssss/backend:v2

    - name: Deploy to EKS
      run: |
        aws eks update-kubeconfig --region us-west-2 --name my-eks-cluster
        kubectl apply -f kubernetes-manifests/
